In [1]:
# %load_ext autoreload

import numpy as np
from tafra import Tafra

# %autoreload 2

In [2]:
t = Tafra({
    'x': np.array([1., 2., 3., 4., 5., 6.]),
    'y': np.array(['one', 'two', 'one', 'two', 'one', 'two'], dtype='object'),
    'z': np.array([0, 0, 0, 1, 1, 1])
})

t

Tafra(data = {
 'x': array([1., 2., 3., 4., 5., 6.]),
 'y': array(['one', 'two', 'one', 'two', 'one', 'two']),
 'z': array([0, 0, 0, 1, 1, 1])},
dtypes = {
 'x': 'float', 'y': 'object', 'z': 'int'},
rows = 6)

In [3]:
import pandas as pd
df = pd.DataFrame(t.data)

df

x    y  z
0  1.0  one  0
1  2.0  two  0
2  3.0  one  0
3  4.0  two  1
4  5.0  one  1
5  6.0  two  1

In [4]:
Tafra.as_tafra(df)

Tafra(data = {
 'x': array([1., 2., 3., 4., 5., 6.]),
 'y': array(['one', 'two', 'one', 'two', 'one', 'two']),
 'z': array([0, 0, 0, 1, 1, 1])},
dtypes = {
 'x': 'float', 'y': 'object', 'z': 'int'},
rows = 6)

Print Options

In [5]:
print(t)

Tafra(data={'x': array([1., 2., 3., 4., 5., 6.]), 'y': array(['one', 'two', 'one', 'two', 'one', 'two'], dtype=object), 'z': array([0, 0, 0, 1, 1, 1])}, dtypes={'x': 'float', 'y': 'object', 'z': 'int'}, rows=6)


In [6]:
t.pprint()

Tafra(data = {
 'x': array([1., 2., 3., 4., 5., 6.]),
 'y': array(['one', 'two', 'one', 'two', 'one', 'two']),
 'z': array([0, 0, 0, 1, 1, 1])},
dtypes = {
 'x': 'float', 'y': 'object', 'z': 'int'},
rows = 6)


In [7]:
t.pprint(indent=4, width=140)

Tafra(data = {
    'x': array([1., 2., 3., 4., 5., 6.]), 'y': array(['one', 'two', 'one', 'two', 'one', 'two']), 'z': array([0, 0, 0, 1, 1, 1])},
dtypes = {
    'x': 'float', 'y': 'object', 'z': 'int'},
rows = 6)


In [8]:
t.head(5)

Tafra(data = {
 'x': array([1., 2., 3., 4., 5.]),
 'y': array(['one', 'two', 'one', 'two', 'one']),
 'z': array([0, 0, 0, 1, 1])},
dtypes = {
 'x': 'float', 'y': 'object', 'z': 'int'},
rows = 5)

Group By:

In [9]:
gb = t.group_by(
    ['y', 'z'], {'x': sum}, {'count': len}
)

gb

Tafra(data = {
 'count': array([2, 1, 2, 1]),
 'x': array([ 4.,  2., 10.,  5.]),
 'y': array(['one', 'two', 'two', 'one']),
 'z': array([0, 0, 1, 1])},
dtypes = {
 'count': 'int', 'x': 'float', 'y': 'object', 'z': 'int'},
rows = 4)

In [10]:
gb = t.group_by(
    ['y', 'z'], {
        'x': sum,
        'new_x': (sum, 'x')
    }, {'count': len}
)

gb

Tafra(data = {
 'count': array([2, 1, 2, 1]),
 'new_x': array([ 4.,  2., 10.,  5.]),
 'x': array([ 4.,  2., 10.,  5.]),
 'y': array(['one', 'two', 'two', 'one']),
 'z': array([0, 0, 1, 1])},
dtypes = {
 'count': 'int', 'new_x': 'float', 'x': 'float', 'y': 'object', 'z': 'int'},
rows = 4)

Transform

In [11]:
tr = t.transform(
    ['y', 'z'], {'x': sum}, {'id': max}
)

tr

Tafra(data = {
 'id': array([0, 1, 0, 2, 3, 2]),
 'x': array([ 4.,  2.,  4., 10.,  5., 10.]),
 'y': array(['one', 'two', 'one', 'two', 'one', 'two']),
 'z': array([0, 0, 0, 1, 1, 1])},
dtypes = {
 'id': 'int', 'x': 'float', 'y': 'object', 'z': 'int'},
rows = 6)

We can set an custom attribute, but it does not point to the `data` item of the same name

In [12]:
t2 = t.copy()
t2.id = np.empty(t2.rows, dtype=int)
t2['id'] = np.empty(t2.rows, dtype=int)
for i, (u, ix, grouped) in enumerate(t.iterate_by(['y', 'z'])):
    t2['x'][ix] = sum(grouped['x'])
    t2.id[ix] = len(grouped['x'])
    t2['id'][ix] = max(grouped['x'])
    
print(f't2.id = array({t2.id})')
t2

t2.id = array([2 1 2 2 1 2])


Tafra(data = {
 'id': array([3, 2, 3, 6, 5, 6]),
 'x': array([ 4.,  2.,  4., 10.,  5., 10.]),
 'y': array(['one', 'two', 'one', 'two', 'one', 'two']),
 'z': array([0, 0, 0, 1, 1, 1])},
dtypes = {
 'id': 'int', 'x': 'float', 'y': 'object', 'z': 'int'},
rows = 6)

Iterate By

In [13]:
print('Iterate By:')
for u, ix, grouped in t.iterate_by(['y']):
    display(grouped)

Iterate By:


Tafra(data = {
 'x': array([1., 3., 5.]),
 'y': array(['one', 'one', 'one']),
 'z': array([0, 0, 1])},
dtypes = {
 'x': 'float', 'y': 'object', 'z': 'int'},
rows = 3)

Tafra(data = {
 'x': array([2., 4., 6.]),
 'y': array(['two', 'two', 'two']),
 'z': array([0, 1, 1])},
dtypes = {
 'x': 'float', 'y': 'object', 'z': 'int'},
rows = 3)

Group By in Interate By

In [14]:
print('Group By in Iterate By:')
for u, ix, grouped in t.iterate_by(['y']):
    display(grouped.group_by(['z'], {'x': sum}))

Group By in Iterate By:


Tafra(data = {
 'x': array([4., 5.]), 'z': array([0, 1])},
dtypes = {
 'x': 'float', 'z': 'int'},
rows = 2)

Tafra(data = {
 'x': array([ 2., 10.]), 'z': array([0, 1])},
dtypes = {
 'x': 'float', 'z': 'int'},
rows = 2)

In [15]:
_t = t.copy()
_t.update(_t.transform(['y'], {}, {'id': max}))

for u, ix, it in t.iterate_by(['y']):
    _t['x'][ix] = it['x'] - np.mean(it['x'])

print('Index Use in Iterate By:')
_t

Index Use in Iterate By:


Tafra(data = {
 'id': array([0, 1, 0, 1, 0, 1]),
 'x': array([-2., -2.,  0.,  0.,  2.,  2.]),
 'y': array(['one', 'two', 'one', 'two', 'one', 'two']),
 'z': array([0, 0, 0, 1, 1, 1])},
dtypes = {
 'id': 'int', 'x': 'float', 'y': 'object', 'z': 'int'},
rows = 6)

In [16]:
print('Group By in Iterate By:')
_t = t.copy()
for u, ix, it in _t.iterate_by(['y']):
    it['x'][0] = 9
    display(it)

_t

Group By in Iterate By:


Tafra(data = {
 'x': array([9., 3., 5.]),
 'y': array(['one', 'one', 'one']),
 'z': array([0, 0, 1])},
dtypes = {
 'x': 'float', 'y': 'object', 'z': 'int'},
rows = 3)

Tafra(data = {
 'x': array([9., 4., 6.]),
 'y': array(['two', 'two', 'two']),
 'z': array([0, 1, 1])},
dtypes = {
 'x': 'float', 'y': 'object', 'z': 'int'},
rows = 3)

Tafra(data = {
 'x': array([1., 2., 3., 4., 5., 6.]),
 'y': array(['one', 'two', 'one', 'two', 'one', 'two']),
 'z': array([0, 0, 0, 1, 1, 1])},
dtypes = {
 'x': 'float', 'y': 'object', 'z': 'int'},
rows = 6)

In [17]:
l = pd.DataFrame.from_dict({
    'x': np.arange(1000),
})

r = pd.DataFrame.from_dict({
    'a': np.tile(np.arange(1000), 1000),
})

l = l.merge(r, how='left', left_on=['x'], right_on=['a'])

In [18]:
l = Tafra({
    'x': np.arange(1000),
})

r = Tafra({
    'a': np.tile(np.arange(1000), 1000),
})

l = l.left_join(r, [('x', 'a', '==')], ['x', 'a'])

In [19]:
l = Tafra({
    'x': np.arange(100),
})

r = Tafra({
    'a': np.tile(np.arange(10), 1000),
})

l = l.cross_join(r, ['x', 'a'])

In [20]:
l = Tafra({
    'x': np.array([1, 2, 3, 4, 5, 6]),
    'y': np.array(['one', 'two', 'one', 'two', 'one', 'two'], dtype='object'),
    'z': np.array([0, 0, 0, 1, 1, 1])
})

r = Tafra({
    'a': np.array([1, 2, 3, 4, 5, 6]),
    'b': np.array(['one', 'two', 'one', 'two', 'one', 'two'], dtype='object'),
    'c': np.array([0, 0, 0, 1, 1, 1])
})

l = l.left_join(r, [('x', 'a', '==')], ['x', 'y', 'a', 'b'])
l

Tafra(data = {
 'a': array([1, 2, 3, 4, 5, 6]),
 'b': array(['one', 'two', 'one', 'two', 'one', 'two']),
 'x': array([1, 2, 3, 4, 5, 6]),
 'y': array(['one', 'two', 'one', 'two', 'one', 'two'])},
dtypes = {
 'a': 'int', 'b': 'object', 'x': 'int', 'y': 'object'},
rows = 6)

In [21]:
l = Tafra({
    'x': np.array([1, 2, 3, 4, 5, 6]),
    'y': np.array(['one', 'two', 'one', 'two', 'one', 'two'], dtype='object'),
    'z': np.array([0, 0, 0, 1, 1, 1])
})

r = Tafra({
    'a': np.array([1, 1, 1, 2, 2, 2]),
    'b': np.array(['one', 'two', 'one', 'two', 'one', 'two'], dtype='object'),
    'c': np.array([0, 0, 0, 1, 1, 1])
})

l = l.left_join(r, [('x', 'a', '==')], ['x', 'y', 'a', 'b'])
l

Tafra(data = {
 'a': array([1, 1, 1, 2, 2, 2, None, None, None, None]),
 'b': array(['one', 'two', 'one', 'two', 'one', 'two', None, None, None, None],
      dtype=object),
 'x': array([1, 1, 1, 2, 2, 2, 3, 4, 5, 6]),
 'y': array(['one', 'one', 'one', 'two', 'two', 'two', 'one', 'two', 'one',
       'two'])},
dtypes = {
 'a': 'object', 'b': 'object', 'x': 'int', 'y': 'object'},
rows = 10)

In [22]:
l = Tafra({
    'x': np.array([1, 2, 3, 4, 5, 6]),
    'y': np.array(['one', 'two', 'one', 'two', 'one', 'two'], dtype='object'),
    'z': np.array([0, 0, 0, 1, 1, 1])
})

r = Tafra({
    'a': np.array([1, 1, 1, 2, 2, 2]),
    '_a': np.array([1, 1, 2, 2, 3, 3]),
    'b': np.array(['one', 'two', 'one', 'two', 'one', 'two'], dtype='object'),
    'c': np.array([0, 0, 0, 1, 1, 1])
})

l = l.left_join(r, [('x', 'a', '=='), ('x', '_a', '==')], ['x', 'y', 'a', 'b'])
l

Tafra(data = {
 'a': array([1, 1, 2, None, None, None, None]),
 'b': array(['one', 'two', 'two', None, None, None, None]),
 'x': array([1, 1, 2, 3, 4, 5, 6]),
 'y': array(['one', 'one', 'two', 'one', 'two', 'one', 'two'])},
dtypes = {
 'a': 'object', 'b': 'object', 'x': 'int', 'y': 'object'},
rows = 7)

In [23]:
l = Tafra({
    'x': np.array([1, 2, 3, 4, 5, 6]),
    'y': np.array(['one', 'two', 'one', 'two', 'one', 'two'], dtype='object'),
    'z': np.array([0, 0, 0, 1, 1, 1])
})

r = Tafra({
    'a': np.array([1, 1, 2, 2, 3, 3]),
    'b': np.array(['one', 'two', 'one', 'two', 'one', 'two'], dtype='object'),
    'c': np.array([0, 0, 0, 1, 1, 1])
})

l = l.left_join(r, [('x', 'a', '<')], ['x', 'y', 'a', 'b'])
l

Tafra(data = {
 'a': array([2, 2, 3, 3, 3, 3, None, None, None, None]),
 'b': array(['one', 'two', 'one', 'two', 'one', 'two', None, None, None, None],
      dtype=object),
 'x': array([1, 1, 1, 1, 2, 2, 3, 4, 5, 6]),
 'y': array(['one', 'one', 'one', 'one', 'two', 'two', 'one', 'two', 'one',
       'two'])},
dtypes = {
 'a': 'object', 'b': 'object', 'x': 'int', 'y': 'object'},
rows = 10)

In [24]:
l = Tafra({
    'x': np.array([1, 2, 3, 4, 5, 6]),
    'y': np.array(['one', 'two', 'one', 'two', 'one', 'two'], dtype='object'),
    'z': np.array([0, 0, 0, 1, 1, 1])
})

r = Tafra({
    'a': np.array([1, 1, 1, 2, 2, 2]),
    'b': np.array(['one', 'two', 'one', 'two', 'one', 'two'], dtype='object'),
    'c': np.array([0, 0, 0, 1, 1, 1])
})

l = l.left_join(r, [('x', 'a', '==')], ['x', 'y', 'a', 'b'])
l

Tafra(data = {
 'a': array([1, 1, 1, 2, 2, 2, None, None, None, None]),
 'b': array(['one', 'two', 'one', 'two', 'one', 'two', None, None, None, None],
      dtype=object),
 'x': array([1, 1, 1, 2, 2, 2, 3, 4, 5, 6]),
 'y': array(['one', 'one', 'one', 'two', 'two', 'two', 'one', 'two', 'one',
       'two'])},
dtypes = {
 'a': 'object', 'b': 'object', 'x': 'int', 'y': 'object'},
rows = 10)

In [25]:
l = Tafra({
    'x': np.array([1, 2, 3, 4, 5, 6]),
    'y': np.array(['one', 'two', 'one', 'two', 'one', 'two'], dtype='object'),
    'z': np.array([0, 0, 0, 1, 1, 1])
})

r = Tafra({
    'a': np.array([1, 2, 3, 4, 5, 6]),
    'b': np.array(['one', 'two', 'one', 'two', 'one', 'two'], dtype='object'),
    'c': np.array([0, 0, 0, 1, 1, 1])
})

l = l.inner_join(r, [('x', 'a', '==')], ['x', 'y', 'a', 'b'])
l

Tafra(data = {
 'a': array([1, 2, 3, 4, 5, 6]),
 'b': array(['one', 'two', 'one', 'two', 'one', 'two']),
 'x': array([1, 2, 3, 4, 5, 6]),
 'y': array(['one', 'two', 'one', 'two', 'one', 'two'])},
dtypes = {
 'a': 'int', 'b': 'object', 'x': 'int', 'y': 'object'},
rows = 6)

In [26]:
l = Tafra({
    'x': np.array([1, 2, 3, 4, 5, 6]),
    'y': np.array(['one', 'two', 'one', 'two', 'one', 'two'], dtype='object'),
    'z': np.array([0, 0, 0, 1, 1, 1])
})

r = Tafra({
    'a': np.array([1, 1, 2, 2, 3, 3]),
    'b': np.array(['one', 'two', 'one', 'two', 'one', 'two'], dtype='object'),
    'c': np.array([0, 0, 0, 1, 1, 1])
})

l = l.inner_join(r, [('x', 'a', '==')], ['x', 'y', 'a', 'b'])
l

Tafra(data = {
 'a': array([1, 1, 2, 2, 3, 3]),
 'b': array(['one', 'two', 'one', 'two', 'one', 'two']),
 'x': array([1, 1, 2, 2, 3, 3]),
 'y': array(['one', 'one', 'two', 'two', 'one', 'one'])},
dtypes = {
 'a': 'int', 'b': 'object', 'x': 'int', 'y': 'object'},
rows = 6)

In [27]:
l = Tafra({
    'x': np.array([1, 2, 3, 4, 5, 6]),
    'y': np.array(['one', 'two', 'one', 'two', 'one', 'two'], dtype='object'),
    'z': np.array([0, 0, 0, 1, 1, 1])
})

r = Tafra({
    'a': np.array([1, 1, 1, 2, 2, 2]),
    'b': np.array(['one', 'two', 'one', 'two', 'one', 'two'], dtype='object'),
    'c': np.array([0, 0, 0, 1, 1, 1])
})

l = l.inner_join(r, [('x', 'a', '==')], ['x', 'y', 'a', 'b'])
l

Tafra(data = {
 'a': array([1, 1, 1, 2, 2, 2]),
 'b': array(['one', 'two', 'one', 'two', 'one', 'two']),
 'x': array([1, 1, 1, 2, 2, 2]),
 'y': array(['one', 'one', 'one', 'two', 'two', 'two'])},
dtypes = {
 'a': 'int', 'b': 'object', 'x': 'int', 'y': 'object'},
rows = 6)

In [28]:
l = Tafra({
    'x': np.array([1, 2, 3, 4, 5, 6]),
    'y': np.array(['one', 'two', 'one', 'two', 'one', 'two'], dtype='object'),
    'z': np.array([0, 0, 0, 1, 1, 1])
})

r = Tafra({
    'a': np.array([1, 1, 1, 2, 2, 2]),
    'b': np.array(['one', 'two', 'one', 'two', 'one', 'two'], dtype='object'),
    'c': np.array([0, 0, 0, 1, 1, 1])
})

l = l.inner_join(r, [('x', 'a', '<=')], ['x', 'y', 'a', 'b'])
l

Tafra(data = {
 'a': array([1, 1, 1, 2, 2, 2, 2, 2, 2]),
 'b': array(['one', 'two', 'one', 'two', 'one', 'two', 'two', 'one', 'two'],
      dtype=object),
 'x': array([1, 1, 1, 1, 1, 1, 2, 2, 2]),
 'y': array(['one', 'one', 'one', 'one', 'one', 'one', 'two', 'two', 'two'],
      dtype=object)},
dtypes = {
 'a': 'int', 'b': 'object', 'x': 'int', 'y': 'object'},
rows = 9)

In [29]:
t0 = t.copy()
try:
    t0.union(_t)
except Exception as e:
    print(e)

In [30]:
t2 = t.copy()
t3 = t.copy()
t3.update_dtypes({'x': float})

In [31]:
t0.union(t2)

Tafra(data = {
 'x': array([1., 2., 3., 4., 5., 6., 1., 2., 3., 4., 5., 6.]),
 'y': array(['one', 'two', 'one', 'two', 'one', 'two', 'one', 'two', 'one',
       'two', 'one', 'two']),
 'z': array([0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1])},
dtypes = {
 'x': 'float', 'y': 'object', 'z': 'int'},
rows = 12)

In [32]:
try:
    t0.union(t3)
except Exception as e:
    print(e)

In [33]:
t3 = t.copy()
t2.union(t3, inplace=True)
t2

Tafra(data = {
 'x': array([1., 2., 3., 4., 5., 6., 1., 2., 3., 4., 5., 6.]),
 'y': array(['one', 'two', 'one', 'two', 'one', 'two', 'one', 'two', 'one',
       'two', 'one', 'two']),
 'z': array([0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1])},
dtypes = {
 'x': 'float', 'y': 'object', 'z': 'int'},
rows = 6)

In [34]:
x = t0[:3]
x['x'][0] = 0
t0['x']

array([0., 2., 3., 4., 5., 6.])

In [35]:
x = t0[slice(0, 3)]
x['x'][0] = 7
t0['x']

array([7., 2., 3., 4., 5., 6.])

In [36]:
z = t0[:3].copy()
z['x'][0] = 9
t0['x']

array([7., 2., 3., 4., 5., 6.])

In [37]:
a = t0[t0['x'] <= 4]
a['x'][1] = 15
print(a['x'])
print(t0['x'])

[ 2. 15.  4.]
[7. 2. 3. 4. 5. 6.]


In [38]:
t0.update_dtypes({'x': float})

In [39]:
t0.update_dtypes({'x': 'float'})

In [40]:
try:
    t0.update_dtypes({'x': 'flot', 'y': 'st'})
except Exception as e:
    print(e)

`flot` is not a valid dtype for `x.`
`st` is not a valid dtype for `y.`



In [41]:
t0.update_dtypes({'x': int})
o = t0.copy()
t0.update(o)
t0

Tafra(data = {
 'x': array([7, 2, 3, 4, 5, 6]),
 'y': array(['one', 'two', 'one', 'two', 'one', 'two']),
 'z': array([0, 0, 0, 1, 1, 1])},
dtypes = {
 'x': 'int', 'y': 'object', 'z': 'int'},
rows = 6)

In [42]:
o.update_dtypes({'x': float})
t0.update(o)
t0

Tafra(data = {
 'x': array([7., 2., 3., 4., 5., 6.]),
 'y': array(['one', 'two', 'one', 'two', 'one', 'two']),
 'z': array([0, 0, 0, 1, 1, 1])},
dtypes = {
 'x': 'float', 'y': 'object', 'z': 'int'},
rows = 6)

Direct assignment to the `_data` `dict()` is not recommended as it bypasses validation.

In [43]:
o._data['x'] = np.arange(5)
try:
    o.__post_init__()
except Exception as e:
    print(e)

`Tafra` must have consistent row counts.


In [44]:
try:
    t0.update(o)
except Exception as e:
    print(e)
t0

Other `Tafra` must have consistent row count. This `Tafra` has 6 rows, other `Tafra` has 5 rows.


Tafra(data = {
 'x': array([7., 2., 3., 4., 5., 6.]),
 'y': array(['one', 'two', 'one', 'two', 'one', 'two']),
 'z': array([0, 0, 0, 1, 1, 1])},
dtypes = {
 'x': 'float', 'y': 'object', 'z': 'int'},
rows = 6)

In [45]:
try:
    t0['x'] = list(range(6))
except Exception as e:
    print(e)
t0

Tafra(data = {
 'x': array([0, 1, 2, 3, 4, 5]),
 'y': array(['one', 'two', 'one', 'two', 'one', 'two']),
 'z': array([0, 0, 0, 1, 1, 1])},
dtypes = {
 'x': 'int', 'y': 'object', 'z': 'int'},
rows = 6)

In [46]:
t0['x'] = np.arange(6)[:, None]

c:\users\dfulford\projects\petbox\tafra\tafra\base.py:361: UserWarning: `np.squeeze(ndarray)` applied to set ndim == 1.
  warnings.warn('`np.squeeze(ndarray)` applied to set ndim == 1.')


In [47]:
try:
    t0['x'] = np.atleast_2d(np.arange(6))
except Exception as e:
    print(e)
t0

c:\users\dfulford\projects\petbox\tafra\tafra\base.py:361: UserWarning: `np.squeeze(ndarray)` applied to set ndim == 1.
  warnings.warn('`np.squeeze(ndarray)` applied to set ndim == 1.')


Tafra(data = {
 'x': array([0, 1, 2, 3, 4, 5]),
 'y': array(['one', 'two', 'one', 'two', 'one', 'two']),
 'z': array([0, 0, 0, 1, 1, 1])},
dtypes = {
 'x': 'int', 'y': 'object', 'z': 'int'},
rows = 6)

In [48]:
t0['x'] = np.atleast_2d(np.arange(6)).T
t0

c:\users\dfulford\projects\petbox\tafra\tafra\base.py:361: UserWarning: `np.squeeze(ndarray)` applied to set ndim == 1.
  warnings.warn('`np.squeeze(ndarray)` applied to set ndim == 1.')


Tafra(data = {
 'x': array([0, 1, 2, 3, 4, 5]),
 'y': array(['one', 'two', 'one', 'two', 'one', 'two']),
 'z': array([0, 0, 0, 1, 1, 1])},
dtypes = {
 'x': 'int', 'y': 'object', 'z': 'int'},
rows = 6)

In [49]:
try:
    t0['x'] = np.atleast_2d(np.arange(6))
except Exception as e:
    print(e)

c:\users\dfulford\projects\petbox\tafra\tafra\base.py:361: UserWarning: `np.squeeze(ndarray)` applied to set ndim == 1.
  warnings.warn('`np.squeeze(ndarray)` applied to set ndim == 1.')


In [50]:
try:
    t0['x'] = np.repeat(np.arange(6)[:, None], repeats=2, axis=1)
except Exception as e:
    print(e)

`ndarray` or `np.squeeze(ndarray)` must have ndim == 1.


In [51]:
t4 = Tafra({
    'x': np.array([1, 2, 3, 4, 5, 6]),
    'y': np.array(['one', 'two', 'one', 'two', 'one', 'two'], dtype='object'),
    'z': np.array([0, 0, 0, 1, 1, 1])
})

t4['d'] = np.array([np.datetime64(_, 'D') for _ in range(6)])

t4

Tafra(data = {
 'd': array(['1970-01-01', '1970-01-02', '1970-01-03', '1970-01-04',
       '1970-01-05', '1970-01-06'], dtype='datetime64[D]'),
 'x': array([1, 2, 3, 4, 5, 6]),
 'y': array(['one', 'two', 'one', 'two', 'one', 'two']),
 'z': array([0, 0, 0, 1, 1, 1])},
dtypes = {
 'd': 'date', 'x': 'int', 'y': 'object', 'z': 'int'},
rows = 6)

In [52]:
tuple(t4.to_records())

((1, 'one', 0, '1970-01-01'),
 (2, 'two', 0, '1970-01-02'),
 (3, 'one', 0, '1970-01-03'),
 (4, 'two', 1, '1970-01-04'),
 (5, 'one', 1, '1970-01-05'),
 (6, 'two', 1, '1970-01-06'))

In [53]:
t4.to_list()

[array([1, 2, 3, 4, 5, 6]),
 array(['one', 'two', 'one', 'two', 'one', 'two'], dtype=object),
 array([0, 0, 0, 1, 1, 1]),
 array(['1970-01-01', '1970-01-02', '1970-01-03', '1970-01-04',
        '1970-01-05', '1970-01-06'], dtype='datetime64[D]')]

In [54]:
t5 = Tafra({'x': np.array([1, 2, None, 4, None])})
t5

Tafra(data = {
 'x': array([1, 2, None, 4, None])},
dtypes = {
 'x': 'object'},
rows = 5)

In [55]:
t5['x'] = t5.coalesce('x', [[1, 2, 3, None, 5], [None, None, None, None, 'five']])
t5

Tafra(data = {
 'x': array([1, 2, 3, 4, 5])},
dtypes = {
 'x': 'object'},
rows = 5)